/**
 * ShopSphere Indian Marketplace Product Dataset
 * Enriched dataset containing 40+ realistic products in Indian Rupees (₹)
 * across 12+ categories with brands, specs, ratings, and discounts.
 */

export const INDIAN_PRODUCTS = [
  // --- MOBILES & SMARTPHONES ---
  {
    id: 101,
    title: "Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB RAM, 256GB Storage)",
    brand: "Samsung",
    category: "Mobiles",
    price: 129999,
    originalPrice: 144999,
    discount: 10,
    rating: { rate: 4.6, count: 3420 },
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80"
    ],
    stock: 12,
    delivery: "Free delivery by Tomorrow",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["200MP Camera with AI Zoom", "Snapdragon 8 Gen 3 for Galaxy", "Embedded S-Pen", "5000 mAh Battery"],
    specifications: { "Brand": "Samsung", "Model": "Galaxy S24 Ultra", "Display": "6.8-inch QHD+ AMOLED 120Hz", "RAM": "12 GB", "Storage": "256 GB", "Battery": "5000 mAh" },
    description: "Experience the ultimate smartphone innovation with Galaxy AI, Titanium frame, 200MP Pro-visual engine camera, and long-lasting battery life."
  },
  {
    id: 102,
    title: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    brand: "Apple",
    category: "Mobiles",
    price: 148900,
    originalPrice: 159900,
    discount: 7,
    rating: { rate: 4.7, count: 4890 },
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80"
    ],
    stock: 8,
    delivery: "Free delivery by 2 Days",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["A17 Pro Chip with 6-core GPU", "Titanium Design with Action Button", "48MP Main Camera with 5x Telephoto", "USB-C Connector"],
    specifications: { "Brand": "Apple", "Model": "iPhone 15 Pro Max", "Display": "6.7-inch Super Retina XDR OLED", "Processor": "A17 Pro Bionic", "Storage": "256 GB", "OS": "iOS 17" },
    description: "Forged in titanium and featuring the groundbreaking A17 Pro chip, customizable Action button, and the most powerful iPhone camera system ever."
  },
  {
    id: 103,
    title: "OnePlus 12 5G (Silky Black, 16GB RAM, 512GB Storage)",
    brand: "OnePlus",
    category: "Mobiles",
    price: 69999,
    originalPrice: 74999,
    discount: 7,
    rating: { rate: 4.5, count: 2150 },
    image: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80"],
    stock: 15,
    delivery: "Free delivery by Tomorrow",
    isFeatured: true,
    isBestSeller: false,
    highlights: ["4th Gen Hasselblad Camera", "Snapdragon 8 Gen 3", "100W SUPERVOOC Charging", "2K 120Hz ProXDR Display"],
    specifications: { "Brand": "OnePlus", "Model": "OnePlus 12", "Display": "6.82-inch 2K AMOLED 120Hz", "RAM": "16 GB", "Storage": "512 GB", "Battery": "5400 mAh" },
    description: "Smooth Beyond Belief. Powered by Snapdragon 8 Gen 3, trinity engine optimization, and 4th Gen Hasselblad Camera System."
  },
  {
    id: 104,
    title: "Redmi Note 13 Pro+ 5G (Fusion Purple, 12GB RAM, 256GB Storage)",
    brand: "Xiaomi",
    category: "Mobiles",
    price: 31999,
    originalPrice: 35999,
    discount: 11,
    rating: { rate: 4.3, count: 5410 },
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80"],
    stock: 25,
    delivery: "Free delivery by Tomorrow",
    isFeatured: false,
    isBestSeller: true,
    highlights: ["200MP OIS 3D Curved AMOLED", "120W HyperCharge", "IP68 Water & Dust Resistance", "MediaTek Dimensity 7200 Ultra"],
    specifications: { "Brand": "Xiaomi", "Model": "Redmi Note 13 Pro+", "Display": "6.67-inch 1.5K 120Hz AMOLED", "RAM": "12 GB", "Storage": "256 GB", "Battery": "5000 mAh" },
    description: "SuperNote revolution with 200MP OIS camera, 120W HyperCharge, 3D Curved AMOLED display, and IP68 rating."
  },

  // --- LAPTOPS & COMPUTERS ---
  {
    id: 105,
    title: "Apple MacBook Air M3 (13.6-inch, 8GB RAM, 256GB SSD) - Space Grey",
    brand: "Apple",
    category: "Laptops",
    price: 104900,
    originalPrice: 114900,
    discount: 8,
    rating: { rate: 4.8, count: 1820 },
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80"],
    stock: 10,
    delivery: "Free delivery by Tomorrow",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["Apple M3 8-core CPU", "18 Hours Battery Life", "Liquid Retina Display", "MagSafe 3 Charging"],
    specifications: { "Brand": "Apple", "Model": "MacBook Air M3", "Processor": "Apple M3 Chip", "RAM": "8 GB Unified", "SSD": "256 GB", "Weight": "1.24 kg" },
    description: "Lean. Mean. M3 machine. Ultra-portable laptop with blazing M3 speed, up to 18 hours of battery life, and vibrant Liquid Retina display."
  },
  {
    id: 106,
    title: "ASUS ROG Strix G16 Gaming Laptop (Intel i7 13th Gen, RTX 4060, 16GB, 1TB SSD)",
    brand: "ASUS",
    category: "Laptops",
    price: 124990,
    originalPrice: 149990,
    discount: 16,
    rating: { rate: 4.6, count: 940 },
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80"],
    stock: 6,
    delivery: "Free delivery by 2 Days",
    isFeatured: true,
    isBestSeller: false,
    highlights: ["NVIDIA GeForce RTX 4060 8GB", "165Hz FHD+ IPS Display", "ROG Intelligent Cooling", "RGB Per-Key Keyboard"],
    specifications: { "Brand": "ASUS", "Model": "ROG Strix G16", "Processor": "Intel Core i7-13650HX", "RAM": "16 GB DDR5", "SSD": "1 TB NVMe", "GPU": "RTX 4060 8GB" },
    description: "Dominate the battlefield with 13th Gen Intel Core i7 processor and NVIDIA GeForce RTX 4060 GPU with MUX Switch."
  },

  // --- ELECTRONICS & AUDIO ---
  {
    id: 107,
    title: "Sony WH-1000XM5 Wireless Industry Leading Noise Canceling Headphones",
    brand: "Sony",
    category: "Electronics",
    price: 26990,
    originalPrice: 34990,
    discount: 22,
    rating: { rate: 4.7, count: 3210 },
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80"],
    stock: 20,
    delivery: "Free delivery by Tomorrow",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["Auto NC Optimizer", "30-Hour Battery Life", "Speak-to-Chat Technology", "Ultra-clear Hands-free Calling"],
    specifications: { "Brand": "Sony", "Model": "WH-1000XM5", "Type": "Over-Ear", "Battery": "30 Hours", "Bluetooth": "v5.2", "NC Processor": "V1 + QN1" },
    description: "Industry-leading Noise Cancellation powered by 8 microphones and Auto NC Optimizer for remarkable sound precision."
  },
  {
    id: 108,
    title: "Apple Watch Series 9 GPS 45mm Midnight Aluminum Case with Sport Band",
    brand: "Apple",
    category: "Electronics",
    price: 41900,
    originalPrice: 44900,
    discount: 6,
    rating: { rate: 4.6, count: 1450 },
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80"],
    stock: 14,
    delivery: "Free delivery by Tomorrow",
    isFeatured: false,
    isBestSeller: true,
    highlights: ["S9 SiP with Double Tap Gesture", "Brighter Always-On Retina Display", "Blood Oxygen & ECG App", "Crash Detection"],
    specifications: { "Brand": "Apple", "Model": "Watch Series 9", "Size": "45mm", "Display": "Always-On OLED", "Water Resistance": "50m" },
    description: "Smarter. Brighter. Mightier. Featuring double tap gesture control, Precision Finding for iPhone, and advanced health sensors."
  },

  // --- HOME APPLIANCES & TVS ---
  {
    id: 109,
    title: "LG 55 inches 4K Ultra HD Smart OLED TV (OLED55C3PSA)",
    brand: "LG",
    category: "TVs",
    price: 119990,
    originalPrice: 169990,
    discount: 29,
    rating: { rate: 4.8, count: 870 },
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80"],
    stock: 5,
    delivery: "Free Scheduled Delivery & Installation",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["α9 AI Processor Gen6", "Self-lighting OLED Pixels", "Dolby Vision IQ & Dolby Atmos", "0.1ms Response Time 120Hz Gaming"],
    specifications: { "Brand": "LG", "Model": "OLED55C3PSA", "Screen Size": "55 Inches", "Resolution": "4K Ultra HD OLED", "Refresh Rate": "120 Hz" },
    description: "Experience self-lit OLED pixels delivering infinite contrast, 100% color fidelity, and α9 AI Processor 4K Gen6 precision sound."
  },
  {
    id: 110,
    title: "LG 8 Kg 5 Star Inverter AI Direct Drive Front Load Washing Machine",
    brand: "LG",
    category: "Appliances",
    price: 36990,
    originalPrice: 48990,
    discount: 24,
    rating: { rate: 4.5, count: 2310 },
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=600&q=80"],
    stock: 12,
    delivery: "Free Scheduled Installation",
    isFeatured: false,
    isBestSeller: true,
    highlights: ["AI DD Motion Technology", "6 Motion Direct Drive", "Steam Allergy Care", "5 Star Energy Rating"],
    specifications: { "Brand": "LG", "Capacity": "8 Kg", "Energy Rating": "5 Star", "Motor": "Inverter Direct Drive", "Max RPM": "1400 RPM" },
    description: "AI DD technology optimizes fabric motion sensing for 18% more fabric care, hygienic steam wash, and energy efficiency."
  },
  {
    id: 111,
    title: "Samsung 324 L 3 Star Frost Free Double Door Refrigerator",
    brand: "Samsung",
    category: "Appliances",
    price: 34990,
    originalPrice: 44990,
    discount: 22,
    rating: { rate: 4.4, count: 1890 },
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80"],
    stock: 9,
    delivery: "Free Scheduled Delivery",
    isFeatured: false,
    isBestSeller: false,
    highlights: ["Convertible 5in1 Modes", "Digital Inverter Compressor", "Twin Cooling Plus", "Coolpack 12 Hours Keep"],
    specifications: { "Brand": "Samsung", "Capacity": "324 Liters", "Energy Rating": "3 Star", "Cooling": "Twin Cooling Plus", "Warranty": "20 Year Compressor" },
    description: "Convertible 5-in-1 modes to convert your freezer into fridge for all fresh food storage needs with 20-year inverter warranty."
  },

  // --- FASHION (MEN'S & WOMEN'S) ---
  {
    id: 112,
    title: "Men's Premium Slim Fit Casual Cotton Shirt - Olive Green",
    brand: "Roadster",
    category: "Men's Fashion",
    price: 899,
    originalPrice: 1999,
    discount: 55,
    rating: { rate: 4.2, count: 6820 },
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80"],
    stock: 50,
    delivery: "Free delivery by Tomorrow",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["100% Breathable Cotton", "Slim Fit Curved Hem", "Button-Down Collar", "Easy Machine Wash"],
    specifications: { "Brand": "Roadster", "Fit": "Slim Fit", "Fabric": "100% Cotton", "Sleeve": "Long Sleeve", "Pattern": "Solid" },
    description: "Crafted from 100% pure breathable cotton fabric, perfect for casual outings and smart weekend styling."
  },
  {
    id: 113,
    title: "Women's Printed Anarkali Kurta Set with Dupatta",
    brand: "BIBA",
    category: "Women's Fashion",
    price: 2499,
    originalPrice: 5999,
    discount: 58,
    rating: { rate: 4.5, count: 4210 },
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80"],
    stock: 35,
    delivery: "Free delivery by Tomorrow",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["Pure Viscose Rayon Fabric", "Traditional Gold Foil Print", "Includes Matching Palazzo & Dupatta", "Ankle Length Flare"],
    specifications: { "Brand": "BIBA", "Style": "Anarkali Kurta Set", "Fabric": "Rayon", "Length": "Ankle Length", "Care": "Dry Clean First" },
    description: "Graceful floral foil printed Anarkali suit set tailored for festive celebrations and wedding occasions."
  },
  {
    id: 114,
    title: "Nike Air Max Solo Men's Running Sneakers - Black & White",
    brand: "Nike",
    category: "Sports",
    price: 6495,
    originalPrice: 8295,
    discount: 21,
    rating: { rate: 4.6, count: 1290 },
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80"],
    stock: 18,
    delivery: "Free delivery by 2 Days",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["Max Air Heel Cushioning", "Breathable Mesh Upper", "Durable Rubber Waffle Outsole", "Lightweight Foam Midsole"],
    specifications: { "Brand": "Nike", "Type": "Sports Running Shoe", "Sole": "Rubber", "Closure": "Lace-Up" },
    description: "Rip through your daily running routines with Max Air heel cushioning and light mesh ventilation."
  },

  // --- BEAUTY & PERSONAL CARE ---
  {
    id: 115,
    title: "Minimalist 10% Vitamin C Face Serum for Radiant Skin (30 ml)",
    brand: "Minimalist",
    category: "Beauty",
    price: 649,
    originalPrice: 699,
    discount: 7,
    rating: { rate: 4.4, count: 9120 },
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80"],
    stock: 60,
    delivery: "Free delivery by Tomorrow",
    isFeatured: false,
    isBestSeller: true,
    highlights: ["Ethyl Ascorbic Acid 10%", "Boosts Skin Glow & Reduces Spots", "Centella Water Soothing Formula", "Dermatologically Tested"],
    specifications: { "Brand": "Minimalist", "Volume": "30 ml", "Skin Type": "All Skin Types", "Form": "Serum" },
    description: "Highly stable Vitamin C serum formulated with Centella Asiatica water for glowing, spot-free skin texture."
  },

  // --- GROCERY & DAILY ESSENTIALS ---
  {
    id: 116,
    title: "Fortune Sunlite Refined Sunflower Oil (5 Liter Can)",
    brand: "Fortune",
    category: "Grocery",
    price: 645,
    originalPrice: 799,
    discount: 19,
    rating: { rate: 4.6, count: 12450 },
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80"],
    stock: 100,
    delivery: "Express 2-Hour Delivery Available",
    isFeatured: false,
    isBestSeller: true,
    highlights: ["Enriched with Vitamin A & D", "Light & Easy to Digest", "High Smoke Point", "100% Pure Sunflower Oil"],
    specifications: { "Brand": "Fortune", "Quantity": "5 Liters", "Form": "Liquid Oil", "Package": "Jar/Can" },
    description: "Light, healthy, and easy to digest refined sunflower oil enriched with vitamins for healthy cooking."
  },

  // --- HOME & FURNITURE ---
  {
    id: 117,
    title: "Wakefit Orthopedic Memory Foam Queen Size Mattress (78x60x6 Inches)",
    brand: "Wakefit",
    category: "Furniture",
    price: 11499,
    originalPrice: 15499,
    discount: 25,
    rating: { rate: 4.6, count: 18450 },
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"],
    stock: 15,
    delivery: "Free Doorstep Delivery",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["10 Years Manufacturer Warranty", "Next-Gen Memory Foam", "Spinal Alignment Support", "Removable Breathable Cover"],
    specifications: { "Brand": "Wakefit", "Dimensions": "78 x 60 x 6 Inches", "Size": "Queen", "Warranty": "10 Years" },
    description: "Designed for spinal alignment and adaptive body contouring so you wake up refreshed every morning."
  }
];

export const CATEGORIES_LIST = [
  { id: "all", name: "All Categories", icon: "🏬" },
  { id: "mobiles", name: "Mobiles", icon: "📱" },
  { id: "laptops", name: "Laptops", icon: "💻" },
  { id: "electronics", name: "Electronics", icon: "🎧" },
  { id: "tvs", name: "TVs", icon: "📺" },
  { id: "appliances", name: "Appliances", icon: "🧺" },
  { id: "mens-fashion", name: "Men's Fashion", icon: "👔" },
  { id: "womens-fashion", name: "Women's Fashion", icon: "👗" },
  { id: "beauty", name: "Beauty", icon: "💄" },
  { id: "grocery", name: "Grocery", icon: "🛒" },
  { id: "sports", name: "Sports", icon: "⚽" },
  { id: "furniture", name: "Furniture", icon: "🛋️" }
];
